# Drupal10, MariaDB, Adminer
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# SQL Server Name: mariadb_d10
# SQL Root Password: mariadb
# SQL Database: drupal10
# SQL User: drupal10
# SQL Password: drupal10
#

version: '3.2'

services:

  drupal:
    image: drupal:10-apache
    container_name: drupal10
    ports:
      - "8080:80"
    restart: always
    volumes:
      - type: bind
        source: ./themes
        target: /var/www/html/themes
      - type: bind
        source: ./modules
        target: /var/www/html/modules

  adminer:
    container_name: adminer_d10
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment: 
      - ADMINER_DEFAULT_SERVER=mariadb_d10
     
  mariadb:
    image: mariadb
    container_name: mariadb_d10
    stop_grace_period: 30s
    working_dir: /host
    volumes:
      - ./db:/host
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=drupal10
      - MYSQL_USER=drupal10
      - MYSQL_PASSWORD=drupal10
    restart: always
