# Drupal8, MariaDB, Adminer
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# SQL Server Name: mariadb
# SQL Root Password: mariadb
# SQL Database: drupal8
# SQL User: mariadb
# SQL Password: mariadb
#
#

version: '3.2'

services:

  drupal:
    image: drupal:8-apache
    container_name: drupal
    ports:
      - "8080:80"
    restart: always
    volumes:
      - type: bind
        source: ./themes
        target: /var/www/html/themes
      # - /var/www/html/modules
      # - /var/www/html/profiles
      # - /var/www/html/themes
      # - /var/www/html/sites
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  mariadb:
    image: mariadb
    container_name: mariadb
    stop_grace_period: 30s
    working_dir: /application
    volumes:
      - ./db:/application
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=drupal8
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    ports:
      - "8082:3306"
    restart: always
